server:
  #랜덤포트 설정하기
  port: 0

spring:
  application:
    name: myfirstservice

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.application.instance_id:${random.value}}
    # 클라이언트가 유레카에 등록된 이후에 등록한 시간마다 하트비트를 전송
    lease-renewal-interval-in-seconds: 1
    # 설정된 시간동안 하트비트를 받지 못하면 인스턴스를 레지스트리에서 제거
    lease-expiration-duration-in-seconds: 2
