server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            message: global filter test
            check: true

      routes:
        - id: first-service
          uri: http://127.0.0.1:9100/
          predicates:
            - Path=/first/**
            - After=2023-11-06T09:40:47.789+09:00[Asia/Seoul]
            - Header=X-PHOTO-VER,3.0.0
          filters:
#            - AddRequestHeader=firstreq,requestheaderfilterTest
#            - AddResponseHeader=firstres,responseheaderfilterTest
#            - MyFilter
            - AddRequestHeader=data,mydata
            - FilterA
            - FilterB
            - FilterC

        - id: second-service
          uri: http://127.0.0.1:9200/
          predicates:
            - Path=/second/**
          filters:
#            - AddRequestHeader=secondreq,requestheaderfilterTest2
#            - AddResponseHeader=secondres,responseheaderfilterTest2
#            - MyFilter
            - AddRequestHeader=data,test
            - FilterA
            - FilterB
            - OrderTestFilter

        - id: third-service
          uri: http://127.0.0.1:9300/
          predicates:
            - Path=/third/**
          filters:
            - AddRequestHeader=secondreq,requestheaderfilterTest2
            - AddResponseHeader=secondres,responseheaderfilterTest2
#            - MyFilter




