SELECT d.DEPARTMENT_NAME  , COUNT(e.EMPLOYEE_ID) 
FROM DEPARTMENTS d , EMPLOYEES e 
WHERE d.DEPARTMENT_ID = e.DEPARTMENT_ID 
AND  TO_CHAR( e.HIRE_DATE , 'yyyy') < '2005'
GROUP BY d.DEPARTMENT_NAME 

SELECT e.HIRE_DATE 
FROM EMPLOYEES e 

SELECT NVL(d.DEPARTMENT_NAME, '<미배치인원>') 부서명
, COUNT(e.EMPLOYEE_ID) 직원수 
FROM DEPARTMENTS d , EMPLOYEES e 
WHERE d.DEPARTMENT_ID(+) = e.DEPARTMENT_ID 
GROUP BY d.DEPARTMENT_NAME 
HAVING COUNT(e.EMPLOYEE_ID) <= 5 
ORDER BY COUNT(e.EMPLOYEE_ID) DESC  

SELECT d.DEPARTMENT_NAME 부서이름  
, COUNT(e.EMPLOYEE_ID) 직원수 
, MAX(e.SALARY) 최대급여
, MIN(e.SALARY) 최소급여
, ROUND ( AVG(e.SALARY) , 2 ) 평균급여
FROM EMPLOYEES e , DEPARTMENTS d 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID 
GROUP BY d.DEPARTMENT_NAME 
HAVING MAX(e.SALARY) <> MIN(e.SALARY)  

SELECT j.JOB_TITLE , SUM(e.SALARY) 
FROM EMPLOYEES e , JOBS j  
WHERE e.JOB_ID  = j.JOB_ID  
GROUP BY j.JOB_TITLE 
HAVING SUM(SALARY) > 30000 
ORDER BY SUM(SALARY) DESC  

SELECT e.EMPLOYEE_ID , e.LAST_NAME , e.SALARY 
FROM EMPLOYEES e 
WHERE e.SALARY < (SELECT AVG(SALARY)
				  FROM EMPLOYEES e2
				  WHERE e2.DEPARTMENT_ID = e.DEPARTMENT_ID ) 
				  
SELECT e.EMPLOYEE_ID , e.FIRST_NAME , e.SALARY 
FROM EMPLOYEES e , DEPARTMENTS d , LOCATIONS l 
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID 
AND d.LOCATION_ID = l.LOCATION_ID 
AND l.CITY = 'Southlake'
AND rownum < 2
ORDER BY SALARY DESC 
-- rownum 개념 물어보고 이해하기
--AND e.SALARY = (SELECT MAX(e2.SALARY) 
--				FROM EMPLOYEES e2 , DEPARTMENTS d2 , LOCATIONS l2 
--				WHERE e2.DEPARTMENT_ID = d2.DEPARTMENT_ID
--				AND d2.LOCATION_ID = l2.LOCATION_ID
--				AND l2.CITY = 'southlake'
--				GROUP BY l2.CITY )

SELECT COUNT(e.MANAGER_ID) 직속부하원수 
, m.EMPLOYEE_ID 관리자사번 
, m.LAST_NAME 관리자이름
FROM EMPLOYEES e , EMPLOYEES m
WHERE e.MANAGER_ID = m.EMPLOYEE_ID 
GROUP BY e.MANAGER_ID , m.EMPLOYEE_ID , m.LAST_NAME  
HAVING COUNT(e.MANAGER_ID) >= 8
ORDER BY 직속부하원수

SELECT d.DEPARTMENT_NAME 
, e.FIRST_NAME 
, e.SALARY 
, round (AVG(e2.SALARY) , 2 )
FROM DEPARTMENTS d , EMPLOYEES e , EMPLOYEES e2 
WHERE d.DEPARTMENT_ID = e.DEPARTMENT_ID  
AND e.SALARY >= 15000
AND e2.DEPARTMENT_ID = e.DEPARTMENT_ID 
GROUP BY d.DEPARTMENT_NAME , e.FIRST_NAME , e.SALARY 

SELECT e.FIRST_NAME , e.LAST_NAME , e.SALARY 
FROM EMPLOYEES e 
WHERE (e.SALARY + 500) > (SELECT AVG(e2.SALARY) 
				  		  FROM EMPLOYEES e2 )
AND (e.SALARY - 500) < (SELECT AVG(e3.SALARY) 
				  		FROM EMPLOYEES e3 )
				  		  
--SELECT AVG(e.SALARY) 
--FROM EMPLOYEES e 





