SELECT * FROM SALGRADE s 

SELECT e.EMPNO , e.ENAME , e.SAL , s.GRADE 
FROM EMP e , SALGRADE s 
WHERE e.SAL >= s.LOSAL AND e.SAL <= s.HISAL 

INSERT INTO emp(empno, ename, HIREDATE) VALUES (7777, 'jin', sysdate);

INSERT INTO emp(empno, ename, HIREDATE) VALUES (8888, 'jbj', sysdate);

COMMIT;

SELECT * FROM EMP e 

SELECT d.DNAME , e.ENAME , e.HIREDATE 
FROM EMP e , DEPT d 
WHERE e.DEPTNO(+) = d.DEPTNO  

SELECT d.DNAME , e.ENAME , e.HIREDATE 
FROM EMP e , DEPT d 
WHERE e.DEPTNO = d.DEPTNO (+)

SELECT FROM 

SELECT NVL(d.DNAME , '신입사원') 부서  , COUNT(e.EMPNO)  FROM EMP e , DEPT d
WHERE d.DEPTNO (+) = e.DEPTNO
GROUP BY d.DNAME 

SELECT e.ENAME , e.SAL , e.HIREDATE , m.ENAME 관리자명 , m.EMPNO , m.MGR 
FROM EMP e ,EMP m
WHERE e.MGR = m.EMPNO 
