server:
  #랜덤포트 설정하기
  port: 0

spring:
  application:
    name: jun

#레지스트리에 서비스 등록할지를 설정 (기본이 true)
eureka:
  client:
    register-with-eureka: true
    # 유레카 서버로부터 인스턴스 정보를 주기적으로 가져올 것인지 설정하는 속성
    # true로 설정하면 갱신된 정보를 주기적으로 받겠다는 의미
    fetch-registry: true

    # 서버의 위치를 등록
    service-url:
      defaultZone: http://192.168.0.16:8761/eureka

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.application.instance_id:${random.value}}
    # 클라이언트가 유레카에 등록된 이후에 등록한 시간마다 하트비트를 전송
    lease-renewal-interval-in-seconds: 1
    # 설정된 시간동안 하트비트를 받지 못하면 인스턴스를 레지스트리에서 제거
    lease-expiration-duration-in-seconds: 2
