server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    # 해당 옵션을 false로 설정해놓으면 연결이 끊킬시 바로 서버를 drop한다
    # 개발용으로만 사용할것
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000