server:
  port: 8001

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://192.168.0.16:8761/eureka

spring:
  application:
    name: gateway-service-exam